module.exports = [
  {
    name: 'Emmanuel',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1937,
    publisher: 'FEB',
  },
  {
    name: 'Brasil, coração do mundo, pátria do evangelho',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1938,
    publisher: 'FEB',
  },
  {
    name: 'A caminho da luz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1938,
    publisher: 'FEB',
  },
  {
    name: 'O consolador',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1940,
    publisher: 'FEB',
  },
  {
    name: 'Renúncia',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1942,
    publisher: 'FEB',
  },
  {
    name: 'Caminho, verdade e vida',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1948,
    publisher: 'FEB',
  },
  {
    name: 'Pão nosso',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1950,
    publisher: 'FEB',
  },
  {
    name: 'Vinha de luz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1951,
    publisher: 'FEB',
  },
  {
    name: 'Fonte viva',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 1952,
    publisher: 'FEB',
  },
  {
    name: 'Ave, Cristo!',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1953,
    publisher: 'FEB',
  },
  {
    name: 'Palavras de Emmanuel',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 1954,
    publisher: 'FEB',
  },
  {
    name: 'Pensamento e vida',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1958,
    publisher: 'FEB',
  },
  {
    name: 'Seara dos médiuns',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1961,
    publisher: 'FEB',
  },
  {
    name: 'Justiça divina',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1962,
    publisher: 'FEB',
  },
  {
    name: 'Palavras de vida eterna',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1964,
    publisher: 'FEB',
  },
  {
    name: 'Ceifa de luz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1972,
    publisher: 'FEB',
  },
  {
    name: 'Assim vencerás',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1978,
    publisher: 'FEB',
  },
  {
    name: 'Amigo',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1979,
    publisher: 'FEB',
  },
  {
    name: 'Algo mais',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1980,
    publisher: 'FEB',
  },
  {
    name: 'Agora é o tempo',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1984,
    publisher: 'FEB',
  },
  {
    name: 'O essencial',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1986,
    publisher: 'FEB',
  },
  {
    name: 'Mediunidade e sintonia',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1986,
    publisher: 'FEB',
  },
  {
    name: 'Alvorada do reino',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: 1988,
    publisher: 'FEB',
  },
  {
    name: 'Palavras de luz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 2014,
    publisher: 'FEB',
  },
  {
    name: 'Gotas de paz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 2019,
    publisher: 'FEB',
  },
  {
    name: 'Alvorada do reino',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 2021,
    publisher: 'FEB',
  },
  {
    name: 'Anotações da mediunidade',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 2021,
    publisher: 'FEB',
  },
  {
    name: 'Livro de respostas',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 2021,
    publisher: 'FEB',
  },
  {
    name: 'Pronto-socorro',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel'],
    datePsychography: '',
    datePublished: 2022,
    publisher: 'FEB',
  },
  {
    name: 'Nosso Lar',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1944,
    publisher: 'FEB',
  },
  {
    name: 'Os mensageiros',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1944,
    publisher: 'FEB',
  },
  {
    name: 'Missionários da luz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1945,
    publisher: 'FEB',
  },
  {
    name: 'Obreiros da vida eterna',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1946,
    publisher: 'FEB',
  },
  {
    name: 'No mundo maior',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1947,
    publisher: 'FEB',
  },
  {
    name: 'Libertação',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1949,
    publisher: 'FEB',
  },
  {
    name: 'Entre a Terra e o Céu',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1954,
    publisher: 'FEB',
  },
  {
    name: 'Nos domínios da mediunidade',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1954,
    publisher: 'FEB',
  },
  {
    name: 'Ação e reação',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1957,
    publisher: 'FEB',
  },
  {
    name: 'Evolução em dois mundos',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1958,
    publisher: 'FEB',
  },
  {
    name: 'Mecanismos da mediunidade',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1960,
    publisher: 'FEB',
  },
  {
    name: 'Sexo e destino',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1965,
    publisher: 'FEB',
  },
  {
    name: 'E a vida continua...',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1968,
    publisher: 'FEB',
  },
  {
    name: 'Agenda cristã',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1948,
    publisher: 'FEB',
  },
  {
    name: 'Conduta espírita',
    authors: ['Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1960,
    publisher: 'FEB',
  },
  {
    name: 'Desobsessão',
    authors: ['Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1964,
    publisher: 'FEB',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. I',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. II',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. III',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. IV',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Opinião Espírita',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1963,
    publisher: 'FEB',
  },
  {
    name: 'Sol nas Almas',
    authors: ['Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1964,
    publisher: 'FEB',
  },
  {
    name: 'Estude e Viva',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1965,
    publisher: 'FEB',
  },
  {
    name: 'Sinal Verde',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1971,
    publisher: 'FEB',
  },
  {
    name: 'Respostas da Vida',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1975,
    publisher: 'FEB',
  },
  {
    name: 'Busca e Acharás',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1976,
    publisher: 'FEB',
  },
  {
    name: 'Endereços da Paz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1982,
    publisher: 'FEB',
  },
  {
    name: 'Cidade no Além',
    authors: ['Francisco Cândido Xavier', 'Heigorina Cunha'],
    spiritualAuthors: ['André Luiz', 'Lucius'],
    datePsychography: 1983,
    publisher: 'FEB',
  },
  {
    name: 'Apostilas da Vida',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1986,
    publisher: 'FEB',
  },
  {
    name: 'Caminho Espírita',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: [
      'Emmanuel',
      'Albino Teixeira',
      'André Luiz',
      'Meimei',
      'Irmão X',
      'Hilário Silva',
      'Bezerra de Menezes',
      'Albino Silva',
      'Fabiano',
    ],
    datePsychography: 1967,
    publisher: 'FEB',
  },
  {
    name: 'Ação e caminho',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1987,
    publisher: 'FEB',
  },
  {
    name: 'A verdade responde',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1990,
    publisher: 'FEB',
  },
  {
    name: 'Tempo e nós',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1993,
    publisher: 'FEB',
  },
  {
    name: 'O Livro dos Espíritos',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1857,
    publisher: 'FEB',
  },
  {
    name: 'O Livro dos Médiuns',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1861,
    publisher: 'FEB',
  },
  {
    name: 'A gênese',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1868,
    publisher: 'FEB',
  },
  {
    name: 'O Evangelho Segundo o Espiritismo',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1864,
    publisher: 'FEB',
  },
  {
    name: 'O Céu e o Inferno',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1865,
    publisher: 'FEB',
  },
  {
    name: 'Obras Póstumas',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1890,
    publisher: 'FEB',
  },
  {
    name: 'O Que é o Espiritismo',
    authors: ['Allan Kardec'],
    spiritualAuthors: ['legião'],
    datePsychography: 1859,
    publisher: 'FEB',
  },
];
